/*steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']   
images:
- 'gcr.io/$PROJECT_ID/gcpdevops' */


steps:
#build the container image
- name: "gcr.io/cloud-bulders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops","."]   
#push container image to gke cluster
- name: "gcr.io/cloud-bulders/docker"
  args: ["push","gcr.io/$PROJECT_ID/gcpdevops"]   
#deploy container name to gke
- name: "gcr.io/cloud-bulders/gke-deploy"
  args: 
  -run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=u-central-c
  - --cluster=gke-gcp-devops
  - --namespace=gcp-devops-prod



/* two steps.fisrt one is build the docker image and 2nd one upload the image to our project.this will run on docker container or an infrasructure that gcp owns , that is cloud build.*/